import type { Course, Event, Testimonial } from './definitions';

export const courses: Course[] = [
  {
    id: '1',
    slug: 'web-design-mastery',
    title: 'Web Design Mastery',
    description: 'Learn the fundamentals of modern web design, from UI/UX principles to responsive layouts.',
    longDescription: 'This comprehensive course covers everything you need to know to become a web design expert. You will learn about user interface and user experience design, color theory, typography, and how to create stunning, responsive websites that work on all devices. The course includes hands-on projects to build your portfolio.',
    category: 'Web Design',
    level: 'Beginner',
    duration: '8 weeks',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'web design',
    syllabus: [
      { title: 'Week 1: Introduction to UI/UX', content: 'Understanding user needs and design principles.' },
      { title: 'Week 2: Wireframing & Prototyping', content: 'Creating low and high-fidelity prototypes.' },
      { title: 'Week 3: Visual Design', content: 'Mastering color, typography, and imagery.' },
      { title: 'Week 4: Responsive Design', content: 'Designing for desktop, tablet, and mobile.' },
    ],
    instructor: {
      name: 'Jane Doe',
      bio: 'Jane is a professional UI/UX designer with over 10 years of experience working with top tech companies. She is passionate about creating intuitive and beautiful user experiences.',
      image: 'https://placehold.co/100x100.png',
    },
    schedule: 'Mondays & Wednesdays, 6:00 PM - 8:00 PM',
  },
  {
    id: '2',
    slug: 'react-for-beginners',
    title: 'React for Beginners',
    description: 'Get started with React, the most popular JavaScript library for building user interfaces.',
    longDescription: 'This course is the perfect starting point for anyone new to React. You will learn the core concepts of React, including components, state, props, and hooks. By the end of the course, you will have built several small projects and a complete single-page application.',
    category: 'Coding',
    level: 'Beginner',
    duration: '6 weeks',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'react javascript',
    syllabus: [
      { title: 'Week 1: JavaScript Refresher & JSX', content: 'Reviewing modern JavaScript and learning JSX syntax.' },
      { title: 'Week 2: Components, Props, and State', content: 'Building and managing reusable UI components.' },
      { title: 'Week 3: React Hooks', content: 'Using useState, useEffect, and other essential hooks.' },
      { title: 'Week 4: Building a Single Page App', content: 'Applying your knowledge to a final project.' },
    ],
    instructor: {
      name: 'John Smith',
      bio: 'John is a senior front-end developer specializing in React. He has a passion for teaching and has helped hundreds of students start their careers in web development.',
      image: 'https://placehold.co/100x100.png',
    },
    schedule: 'Tuesdays & Thursdays, 7:00 PM - 9:00 PM',
  },
  {
    id: '3',
    slug: 'robotics-101',
    title: 'Robotics 101',
    description: 'An introduction to the exciting world of robotics, from basic circuits to programming your first robot.',
    longDescription: 'Dive into the fundamentals of robotics in this hands-on course. You will learn about electronic components, microcontroller programming with Arduino, and how to build and control your own robot. No prior experience in electronics or programming is required.',
    category: 'Robotics',
    level: 'Beginner',
    duration: '10 weeks',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'robotics circuit',
    syllabus: [
      { title: 'Weeks 1-2: Basic Electronics', content: 'Understanding circuits, sensors, and actuators.' },
      { title: 'Weeks 3-5: Arduino Programming', content: 'Learning to code for microcontrollers.' },
      { title: 'Weeks 6-8: Building Your Robot', content: 'Assembling the chassis and connecting components.' },
      { title: 'Weeks 9-10: Final Project', content: 'Programming your robot to perform a complex task.' },
    ],
    instructor: {
      name: 'Emily White',
      bio: 'Emily is a robotics engineer and educator with a love for tinkering and building. She has competed in several international robotics competitions and enjoys sharing her knowledge with beginners.',
      image: 'https://placehold.co/100x100.png',
    },
    schedule: 'Saturdays, 10:00 AM - 1:00 PM',
  },
    {
    id: '4',
    slug: 'advanced-python',
    title: 'Advanced Python Programming',
    description: 'Take your Python skills to the next level with advanced topics like decorators, generators, and concurrency.',
    longDescription: 'This course is for developers who are already comfortable with Python basics. We will explore advanced language features, design patterns, and best practices for writing clean, efficient, and maintainable Python code. Topics include functional programming, object-oriented design, and performance optimization.',
    category: 'Coding',
    level: 'Advanced',
    duration: '8 weeks',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'python code',
    syllabus: [
      { title: 'Week 1: Advanced Functions', content: 'Decorators, generators, and context managers.' },
      { title: 'Week 2: Metaclasses and Descriptors', content: 'Understanding Python\'s object model.' },
      { title: 'Week 3: Concurrency', content: 'Multithreading, multiprocessing, and asyncio.' },
      { title: 'Week 4: Performance Optimization', content: 'Profiling and speeding up your code.' },
    ],
    instructor: {
      name: 'Michael Brown',
      bio: 'Michael is a principal software engineer with over 15 years of experience using Python for everything from web backends to data science. He is a frequent speaker at Python conferences.',
      image: 'https://placehold.co/100x100.png',
    },
    schedule: 'Mondays, 6:30 PM - 8:30 PM',
  },
];

export const events: Event[] = [
  {
    id: '1',
    title: 'Intro to Web Development Workshop',
    date: '2024-08-15',
    description: 'A free 2-hour workshop covering the basics of HTML, CSS, and JavaScript. Perfect for absolute beginners!',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'web development',
  },
  {
    id: '2',
    title: 'Robotics Open House',
    date: '2024-09-01',
    description: 'Come see our robotics lab, meet the instructors, and watch live demos of student projects. Fun for all ages!',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'robotics lab',
  },
  {
    id: '3',
    title: 'Webinar: The Future of AI in Design',
    date: '2024-09-10',
    description: 'Join our expert panel as they discuss how artificial intelligence is changing the field of web and graphic design.',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'ai design',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah L.',
    course: 'Web Design Mastery',
    quote: 'This course was a game-changer for me. I went from knowing nothing about web design to landing my first freelance client before the course even ended!',
    avatar: 'https://placehold.co/48x48.png',
  },
  {
    id: '2',
    name: 'David C.',
    course: 'React for Beginners',
    quote: 'The instructor was fantastic and broke down complex concepts into easy-to-understand pieces. I finally feel confident in my React skills.',
    avatar: 'https://placehold.co/48x48.png',
  },
  {
    id: '3',
    name: 'Maria G.',
    course: 'Robotics 101',
    quote: 'I had so much fun building my own robot! The hands-on projects were the best part. Highly recommend this course to anyone curious about robotics.',
    avatar: 'https://placehold.co/48x48.png',
  },
    {
    id: '4',
    name: 'Alex Johnson',
    course: 'Advanced Python Programming',
    quote: 'The depth of knowledge from the instructor was incredible. I learned so many new techniques that I was able to apply at my job immediately.',
    avatar: 'https://placehold.co/48x48.png',
  },
];
