import type { Course, Event, Testimonial } from './definitions';

export const courses: Course[] = [
  {
    id: '1',
    slug: 'web-design-mastery',
    title: 'Web Design Mastery',
    description: 'Learn the fundamentals of modern web design, from UI/UX principles to responsive layouts.',
    longDescription: 'This comprehensive course covers everything you need to know to become a web design expert. You will learn about user interface and user experience design, color theory, typography, and how to create stunning, responsive websites that work on all devices. The course includes hands-on projects to build your portfolio.',
    category: 'Web Design',
    level: 'Beginner',
    duration: '8 weeks',
    image: '/web.jpg',
    dataAiHint: 'web design',
    syllabus: [
      { title: 'Week 1: Introduction to UI/UX', content: 'Understanding user needs and design principles.' },
      { title: 'Week 2: Wireframing & Prototyping', content: 'Creating low and high-fidelity prototypes.' },
      { title: 'Week 3: Visual Design', content: 'Mastering color, typography, and imagery.' },
      { title: 'Week 4: Responsive Design', content: 'Designing for desktop, tablet, and mobile.' },
    ],
    instructor: {
      name: 'Jane Doe',
      bio: 'Jane is a professional UI/UX designer with over 10 years of experience working with top tech companies. She is passionate about creating intuitive and beautiful user experiences.',
      image: 'https://placehold.co/100x100.png',
    },
    schedule: 'Mondays & Wednesdays, 6:00 PM - 8:00 PM',
  },
  {
    id: '2',
    slug: 'react-for-beginners',
    title: 'React for Beginners',
    description: 'Get started with React, the most popular JavaScript library for building user interfaces.',
    longDescription: 'This course is the perfect starting point for anyone new to React. You will learn the core concepts of React, including components, state, props, and hooks. By the end of the course, you will have built several small projects and a complete single-page application.',
    category: 'Coding',
    level: 'Beginner',
    duration: '6 weeks',
    image: '/react.jpg',
    dataAiHint: 'react javascript',
    syllabus: [
      { title: 'Week 1: JavaScript Refresher & JSX', content: 'Reviewing modern JavaScript and learning JSX syntax.' },
      { title: 'Week 2: Components, Props, and State', content: 'Building and managing reusable UI components.' },
      { title: 'Week 3: React Hooks', content: 'Using useState, useEffect, and other essential hooks.' },
      { title: 'Week 4: Building a Single Page App', content: 'Applying your knowledge to a final project.' },
    ],
    instructor: {
      name: 'John Smith',
      bio: 'John is a senior front-end developer specializing in React. He has a passion for teaching and has helped hundreds of students start their careers in web development.',
      image: 'https://placehold.co/100x100.png',
    },
    schedule: 'Tuesdays & Thursdays, 7:00 PM - 9:00 PM',
  },
  {
    id: '3',
    slug: 'robotics-101',
    title: 'Robotics 101',
    description: 'An introduction to the exciting world of robotics, from basic circuits to programming your first robot.',
    longDescription: 'Dive into the fundamentals of robotics in this hands-on course. You will learn about electronic components, microcontroller programming with Arduino, and how to build and control your own robot. No prior experience in electronics or programming is required.',
    category: 'Robotics',
    level: 'Beginner',
    duration: '10 weeks',
    image: '/robotics.jpg',
    dataAiHint: 'robotics circuit',
    syllabus: [
      { title: 'Weeks 1-2: Basic Electronics', content: 'Understanding circuits, sensors, and actuators.' },
      { title: 'Weeks 3-5: Arduino Programming', content: 'Learning to code for microcontrollers.' },
      { title: 'Weeks 6-8: Building Your Robot', content: 'Assembling the chassis and connecting components.' },
      { title: 'Weeks 9-10: Final Project', content: 'Programming your robot to perform a complex task.' },
    ],
    instructor: {
      name: 'Emily White',
      bio: 'Emily is a robotics engineer and educator with a love for tinkering and building. She has competed in several international robotics competitions and enjoys sharing her knowledge with beginners.',
      image: 'https://placehold.co/100x100.png',
    },
    schedule: 'Saturdays, 10:00 AM - 1:00 PM',
  },
  {
    id: '5',
    slug: 'python-programming-for-everyone',
    title: 'Python for Everyone',
    description: 'Master the fundamentals of Python, one of the most versatile and in-demand programming languages.',
    longDescription: 'This course provides a gentle yet thorough introduction to Python programming. You will learn about data types, control flow, functions, and object-oriented programming. The course is packed with real-world examples and exercises to solidify your understanding.',
    category: 'Coding',
    level: 'Beginner',
    duration: '8 weeks',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'python programming',
    syllabus: [
      { title: 'Week 1: Python Basics', content: 'Variables, data types, and operators.' },
      { title: 'Week 2: Control Flow', content: 'Conditional statements and loops.' },
      { title: 'Week 3: Functions and Modules', content: 'Writing and importing reusable code.' },
      { title: 'Week 4: Data Structures', content: 'Working with lists, tuples, and dictionaries.' },
    ],
    instructor: {
      name: 'Alex Ray',
      bio: 'Alex is a data scientist with a passion for Python and teaching. He believes coding should be accessible to everyone.',
      image: 'https://placehold.co/100x100.png',
    },
    schedule: 'Wednesdays & Fridays, 5:00 PM - 7:00 PM',
  },
  {
    id: '6',
    slug: 'c-programming-essentials',
    title: 'C Programming Essentials',
    description: 'Learn the foundational concepts of C, a powerful language that underpins many modern systems.',
    longDescription: 'Gain a deep understanding of programming by learning C. This course covers pointers, memory management, data structures, and the fundamentals of systems programming. It is an excellent choice for aspiring software engineers and computer science students.',
    category: 'Coding',
    level: 'Intermediate',
    duration: '10 weeks',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'c language code',
    syllabus: [
      { title: 'Weeks 1-2: Core Concepts', content: 'Syntax, data types, and control structures.' },
      { title: 'Weeks 3-5: Pointers and Memory', content: 'Mastering memory allocation and pointers.' },
      { title: 'Weeks 6-8: Data Structures in C', content: 'Implementing lists, stacks, and queues.' },
      { title: 'Weeks 9-10: File I/O', content: 'Working with files and streams.' },
    ],
    instructor: {
      name: 'David Lee',
      bio: 'David is a systems programmer with 20 years of experience. He has contributed to several major open-source projects written in C.',
      image: 'https://placehold.co/100x100.png',
    },
    schedule: 'Tuesdays, 6:00 PM - 9:00 PM',
  },
  {
    id: '7',
    slug: 'cyber-security-fundamentals',
    title: 'Cyber Security Fundamentals',
    description: 'Understand the basics of cyber security and learn how to protect digital systems from threats.',
    longDescription: 'In an increasingly digital world, cyber security is more important than ever. This course introduces you to the core principles of digital security, including threat analysis, network security, cryptography, and ethical hacking. You will learn to think like a security professional and protect against common vulnerabilities.',
    category: 'Cyber Security',
    level: 'Beginner',
    duration: '12 weeks',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'cyber security',
    syllabus: [
      { title: 'Weeks 1-3: Intro to Security', content: 'Threats, vulnerabilities, and risk management.' },
      { title: 'Weeks 4-6: Network Security', content: 'Securing networks with firewalls and IDS.' },
      { title: 'Weeks 7-9: Cryptography Basics', content: 'Understanding encryption and hashing.' },
      { title: 'Weeks 10-12: Ethical Hacking', content: 'Penetration testing and vulnerability assessment.' },
    ],
    instructor: {
      name: 'Jessica Chen',
      bio: 'Jessica is a certified ethical hacker and security consultant. She is dedicated to making the digital world a safer place through education.',
      image: 'https://placehold.co/100x100.png',
    },
    schedule: 'Thursdays, 6:00 PM - 9:00 PM',
  },
  {
    id: '8',
    slug: 'cpp-programming-essentials',
    title: 'C++ Programming Essentials',
    description: 'Learn C++, the powerful object-oriented language behind game engines and high-performance apps.',
    longDescription: 'This course covers the core concepts of C++, from basic syntax to object-oriented principles like classes, inheritance, and polymorphism. It is ideal for those looking to get into game development, high-performance computing, or systems software. You will work on practical projects to build a strong foundation in C++.',
    category: 'Coding',
    level: 'Intermediate',
    duration: '12 weeks',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'c++ code',
    syllabus: [
      { title: 'Weeks 1-3: C++ Basics', content: 'Syntax, control flow, and functions.' },
      { title: 'Weeks 4-6: Object-Oriented Programming', content: 'Classes, objects, and encapsulation.' },
      { title: 'Weeks 7-9: Inheritance and Polymorphism', content: 'Building complex class hierarchies.' },
      { title: 'Weeks 10-12: Standard Template Library (STL)', content: 'Using containers, iterators, and algorithms.' },
    ],
    instructor: {
      name: 'Chris Evans',
      bio: 'Chris is a software architect with extensive experience in C++ for building high-performance applications. He is a strong advocate for modern C++ practices.',
      image: 'https://placehold.co/100x100.png',
    },
    schedule: 'Fridays, 6:00 PM - 9:00 PM',
  },
  {
    id: '9',
    slug: 'embedded-c-programming',
    title: 'Embedded C Programming',
    description: 'Learn C programming for microcontrollers and embedded systems. A hands-on approach to real-world hardware.',
    longDescription: 'This course bridges the gap between C programming and hardware. You will learn how to write efficient C code for resource-constrained embedded systems, interface with peripherals like GPIO, timers, and serial ports, and understand the fundamentals of embedded software development. This is a practical course for anyone looking to get into IoT, robotics, or firmware development.',
    category: 'Coding',
    level: 'Intermediate',
    duration: '10 weeks',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'microcontroller circuit',
    syllabus: [
      { title: 'Weeks 1-2: Intro to Embedded Systems', content: 'Microcontroller architecture and development toolchains.' },
      { title: 'Weeks 3-4: C for Embedded Systems', content: 'Bit manipulation, memory-mapped I/O, and data structures.' },
      { title: 'Weeks 5-7: Peripherals and Interfaces', content: 'Working with GPIO, UART, I2C, and SPI.' },
      { title: 'Weeks 8-10: Real-Time Concepts & Project', content: 'Interrupts, timers, and a final hands-on project.' },
    ],
    instructor: {
      name: 'Mark Roberts',
      bio: 'Mark is an embedded systems engineer with over 15 years of experience developing firmware for consumer electronics and industrial automation. He is passionate about making hardware accessible to software developers.',
      image: 'https://placehold.co/100x100.png',
    },
    schedule: 'Mondays, 7:00 PM - 9:30 PM',
  },
];

export const events: Event[] = [
  {
    id: '1',
    title: 'Intro to Web Development Workshop',
    date: '2024-08-15',
    description: 'A free 2-hour workshop covering the basics of HTML, CSS, and JavaScript. Perfect for absolute beginners!',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'web development',
  },
  {
    id: '2',
    title: 'Robotics Open House',
    date: '2024-09-01',
    description: 'Come see our robotics lab, meet the instructors, and watch live demos of student projects. Fun for all ages!',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'robotics lab',
  },
  {
    id: '3',
    title: 'Webinar: The Future of AI in Design',
    date: '2024-09-10',
    description: 'Join our expert panel as they discuss how artificial intelligence is changing the field of web and graphic design.',
    image: 'https://placehold.co/400x225.png',
    dataAiHint: 'ai design',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah L.',
    course: 'Web Design Mastery',
    quote: 'This course was a game-changer for me. I went from knowing nothing about web design to landing my first freelance client before the course even ended!',
    avatar: 'https://placehold.co/48x48.png',
  },
  {
    id: '2',
    name: 'David C.',
    course: 'React for Beginners',
    quote: 'The instructor was fantastic and broke down complex concepts into easy-to-understand pieces. I finally feel confident in my React skills.',
    avatar: 'https://placehold.co/48x48.png',
  },
  {
    id: '3',
    name: 'Maria G.',
    course: 'Robotics 101',
    quote: 'I had so much fun building my own robot! The hands-on projects were the best part. Highly recommend this course to anyone curious about robotics.',
    avatar: 'https://placehold.co/48x48.png',
  },
    {
    id: '4',
    name: 'Alex Johnson',
    course: 'Advanced Python Programming',
    quote: 'The depth of knowledge from the instructor was incredible. I learned so many new techniques that I was able to apply at my job immediately.',
    avatar: 'https://placehold.co/48x48.png',
  },
];
